#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["sexpdata>=1.0"]
# ///
"""Extract case-relevant geometry from a KiCad PCB into an OpenSCAD data file.

Usage: uv run kicad2scad.py <pcb.kicad_pcb> <board_data.scad>

Coordinates are converted from KiCad (origin top-left, y down) to a
board-local frame: origin at the board's lower-left corner, y up, so an
OpenSCAD top view looks like the KiCad editor view.
"""
import sys
from sexpdata import loads, Symbol


def key(x):
    return x[0].value() if isinstance(x, list) and x and isinstance(x[0], Symbol) else None


def find(node, k):
    return [c for c in node if key(c) == k]


def prop(node, k):
    r = find(node, k)
    return r[0][1:] if r else None


def properties(fp):
    return {p[1]: p[2] for p in find(fp, "property") if len(p) > 2 and isinstance(p[1], str)}


def board_outline(doc):
    rects = [c for c in doc if key(c) == "gr_rect" and prop(c, "layer")[0] == "Edge.Cuts"]
    if len(rects) != 1:
        raise SystemExit("expected exactly one Edge.Cuts rectangle, found %d" % len(rects))
    (x0, y0), (x1, y1) = prop(rects[0], "start"), prop(rects[0], "end")
    return min(x0, x1), min(y0, y1), max(x0, x1), max(y0, y1)


def main(src, dst):
    doc = loads(open(src).read())
    ox0, oy0, ox1, oy1 = board_outline(doc)
    thickness = prop(find(doc, "general")[0], "thickness")[0]
    to_board = lambda x, y: (round(x - ox0, 3), round(oy1 - y, 3))

    holes, headers, parts = [], [], []
    for fp in find(doc, "footprint"):
        name = fp[1]
        at = prop(fp, "at")
        x, y = at[0], at[1]
        rot = at[2] if len(at) > 2 else 0
        props = properties(fp)
        ref = props.get("Reference", "?")
        if name.startswith("MountingHole:"):
            drill = prop(find(fp, "pad")[0], "drill")[0]
            holes.append((ref, *to_board(x, y), drill))
        elif "PinHeader_1x04" in name:
            pads = [prop(p, "at") for p in find(fp, "pad")]
            xs = [x + p[0] for p in pads]
            ys = [y + p[1] for p in pads]
            headers.append((ref, *to_board(min(xs), max(ys)), *to_board(max(xs), min(ys))))
        crt = [g for g in find(fp, "fp_rect") + find(fp, "fp_circle") if "CrtYd" in prop(g, "layer")[0]]
        if crt:
            if key(crt[0]) == "fp_circle":
                (cx, cy), (ex_, ey_) = prop(crt[0], "center"), prop(crt[0], "end")
                r = ((ex_ - cx) ** 2 + (ey_ - cy) ** 2) ** 0.5
                sx, sy, ex, ey = cx - r, cy - r, cx + r, cy + r
            else:
                (sx, sy), (ex, ey) = prop(crt[0], "start"), prop(crt[0], "end")
            # rotate courtyard about footprint origin, then translate
            import math
            a = math.radians(rot)
            pts = [(sx, sy), (ex, sy), (ex, ey), (sx, ey)]
            rp = [(x + px * math.cos(a) + py * math.sin(a), y - px * math.sin(a) + py * math.cos(a)) for px, py in pts]
            bx = [to_board(px, py)[0] for px, py in rp]
            by = [to_board(px, py)[1] for px, py in rp]
            parts.append((ref, props.get("Value", ""), round(min(bx), 3), round(min(by), 3), round(max(bx), 3), round(max(by), 3)))

    holes.sort()
    headers.sort()
    parts.sort()
    with open(dst, "w") as f:
        f.write("// GENERATED by kicad2scad.py from %s -- do not edit by hand.\n" % src.split("/")[-1])
        f.write("// Board-local coordinates: origin lower-left, y up, millimetres.\n\n")
        f.write("pcb_size = [%s, %s];\n" % (round(ox1 - ox0, 3), round(oy1 - oy0, 3)))
        f.write("pcb_thickness = %s;\n\n" % thickness)
        f.write("// [ref, x, y, drill]\n")
        f.write("pcb_holes = [\n" + "".join('  ["%s", %s, %s, %s],\n' % h for h in holes) + "];\n\n")
        f.write("// [ref, x0, y0, x1, y1] -- pad-centre extents of the 1x4 LED headers\n")
        f.write("pcb_headers = [\n" + "".join('  ["%s", %s, %s, %s, %s],\n' % h for h in headers) + "];\n\n")
        f.write("// [ref, value, x0, y0, x1, y1] -- courtyard extents of components\n")
        f.write("pcb_parts = [\n" + "".join('  ["%s", "%s", %s, %s, %s, %s],\n' % p for p in parts) + "];\n")
    print("wrote", dst, "size", (ox1 - ox0, oy1 - oy0), "holes", len(holes), "headers", len(headers), "parts", len(parts))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
