[platformio]
default_envs = esp32-c3-supermini

[env:esp32-c3-supermini]
platform = espressif32@6.10.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DFIRMWARE_VERSION=\"2.0.1\"
lib_deps =
  knolleary/PubSubClient@2.8
  tzapu/WiFiManager@2.0.17
  bblanchon/ArduinoJson@7.3.1
  adafruit/Adafruit NeoPixel@1.12.5
test_framework = unity

[env:native]
platform = native
lib_deps = bblanchon/ArduinoJson@7.3.1
test_framework = unity
test_build_src = no
